#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from poly_robot.llm_policy import load_calibration_policy  # noqa: E402
from poly_robot.replay_harness import load_events_from_jsonl  # noqa: E402
from poly_robot.scenario_matrix import build_scenario_matrix_report  # noqa: E402
from poly_robot.scenario_pack import load_scenario_pack  # noqa: E402
from poly_robot.schemas import STRESS_CAMPAIGN_REPORT_SCHEMA_VERSION  # noqa: E402
from poly_robot.stress_certification import build_stress_certification_report  # noqa: E402


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="milliseconds")


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_profile_payload(profile_path: Path) -> tuple[dict, dict]:
    payload = _load_json(profile_path)
    values = payload.get("values")
    if not isinstance(values, dict):
        raise ValueError(f"Profile values must be an object in {profile_path}")
    return payload, values


def _parse_scenario_list(raw: str | None) -> list[str] | None:
    if raw is None:
        return None
    names = [item.strip() for item in raw.split(",") if item.strip()]
    return names or None


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run Poly-Robot stress campaign matrix and emit a certification artifact "
            "with threshold-based PASS/FAIL decisions."
        )
    )
    parser.add_argument(
        "--events", type=Path, required=True, help="Path to replay event JSONL file."
    )
    parser.add_argument(
        "--profile",
        type=Path,
        default=ROOT_DIR
        / "config"
        / "parameters"
        / "profiles"
        / "mvp_test_token.v1.json",
        help="Path to parameter profile JSON.",
    )
    parser.add_argument(
        "--calibration-policy",
        type=Path,
        default=ROOT_DIR / "config" / "calibration" / "llm_reliability.v1.json",
        help="Path to calibration reliability policy JSON.",
    )
    parser.add_argument(
        "--scenario-pack",
        type=Path,
        default=ROOT_DIR / "config" / "replay" / "scenario_pack.v1.json",
        help="Path to replay scenario pack JSON.",
    )
    parser.add_argument(
        "--scenarios",
        type=str,
        required=False,
        help="Optional comma-separated list of scenarios. Defaults to all scenarios.",
    )
    parser.add_argument(
        "--bankroll",
        type=float,
        default=1000.0,
        help="Initial bankroll used in replay simulation.",
    )
    parser.add_argument(
        "--soak-summary",
        type=Path,
        required=False,
        help="Optional soak summary JSON artifact generated by run_runtime_soak.py.",
    )
    parser.add_argument(
        "--thresholds",
        type=Path,
        required=False,
        help="Optional JSON file overriding certification thresholds.",
    )
    parser.add_argument(
        "--matrix-output",
        type=Path,
        required=False,
        help="Optional path to persist stress matrix report JSON.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=False,
        help="Optional path to persist stress campaign + certification JSON artifact.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    profile_payload, parameters = _load_profile_payload(args.profile)
    calibration_policy_payload = _load_json(args.calibration_policy)
    calibration_policy = load_calibration_policy(args.calibration_policy)
    scenario_pack = load_scenario_pack(args.scenario_pack)
    base_events = load_events_from_jsonl(args.events)
    selected_scenarios = _parse_scenario_list(args.scenarios)

    matrix_report = build_scenario_matrix_report(
        base_events=base_events,
        parameters=parameters,
        calibration_policy=calibration_policy,
        profile_payload=profile_payload,
        calibration_policy_payload=calibration_policy_payload,
        scenario_pack=scenario_pack,
        scenario_pack_path=str(args.scenario_pack),
        events_path=str(args.events),
        profile_path=str(args.profile),
        calibration_policy_path=str(args.calibration_policy),
        bankroll=args.bankroll,
        scenario_names=selected_scenarios,
    )

    soak_summary = _load_json(args.soak_summary) if args.soak_summary else None
    thresholds = _load_json(args.thresholds) if args.thresholds else None
    certification = build_stress_certification_report(
        matrix_report=matrix_report,
        soak_summary=soak_summary,
        thresholds=thresholds,
        metadata={
            "events_path": str(args.events),
            "profile_path": str(args.profile),
            "calibration_policy_path": str(args.calibration_policy),
            "scenario_pack_path": str(args.scenario_pack),
            "soak_summary_path": str(args.soak_summary) if args.soak_summary else None,
            "thresholds_path": str(args.thresholds) if args.thresholds else None,
        },
    )

    campaign_report = {
        "schema_version": STRESS_CAMPAIGN_REPORT_SCHEMA_VERSION,
        "generated_at": _utc_now_iso(),
        "matrix_report": matrix_report,
        "soak_summary": soak_summary,
        "certification": certification,
    }

    if args.matrix_output:
        args.matrix_output.write_text(
            json.dumps(matrix_report, indent=2) + "\n", encoding="utf-8"
        )
    if args.output:
        args.output.write_text(
            json.dumps(campaign_report, indent=2) + "\n", encoding="utf-8"
        )

    aggregate = matrix_report["aggregate"]
    print(
        "Stress certification complete: "
        f"scenarios={aggregate['scenario_count']} "
        f"total_allowed_trades={aggregate['total_allowed_trades']} "
        f"certification_status={certification['overall_status']} "
        f"certification_hash={certification['evidence']['certification_hash'][:12]}"
    )
    return 0 if certification["overall_status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
